CREATE TABLE IF NOT EXISTS identity_cards (
    id VARCHAR(255) NOT NULL PRIMARY KEY,
    customer_id SMALLINT NOT NULL,
    provided_at DATETIME NOT NULL,
    active SMALLINT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL ON UPDATE CURRENT_TIMESTAMP
);
